use different name for lua because of conflict
Fixes error:
org.tarantool.TarantoolException: Failed to dynamically load module '':
/tmp/tntTsVHfi/linkbench.so: invalid ELF header

Because of `box.schema.func.create('linkbench', ...` tarantool checks
`linkbench.lua` first and not `linkbench.so`.